### DISCUSSION TITLE
Using config.toml to map registries for doc builds inside the container

### DISCUSSION THREAD

**Discussion by mjpieters** [kellnr/kellnr#335] [Ideas]
I've managed to make rustdoc builds work without the need for external access, by mapping both crates.io and the private registry to localhost in /root/.cargo/config.toml:

```toml
[source.crates-io]
replace-with = "local-cratesio"
[source.local-cratesio]
registry = "sparse+http://localhost/api/v1/cratesio/"

[source.private]
registry = "sparse+https://EXTERNAL_HOSTNAME/api/v1/crates/"
replace-with = "local-private"
[source.local-private]
registry = "sparse+http://localhost/api/v1/crates/"
```

Replace `EXTERNAL_HOSTNAME` with the hostname that you use for your private kellnr registry _in your crates_. Cargo then replaces this URL to look up the crates via localhost.

Hopefully this is helpful for others here.
