### DISCUSSION TITLE
Github dependabot setup with Kellnr

### DISCUSSION THREAD

**Discussion by jrudolph** [kellnr/kellnr#354] [General]
Has someone figured out how to configure a kellnr based private registry for use with dependabot on github since they added support for private registries a few days ago (see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/guidance-for-the-configuration-of-private-registries-for-dependabot#cargo)?

We tried to use this configuration:

```
version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    registries:
      - kellnr
    schedule:
      interval: daily

registries:
  kellnr:
    type: cargo-registry
    registry: kellnr
    url: https://<host>/api/v1/crates/
    token: "Token ${{secrets.CRATES_TOKEN}}"
```

but it fails with a 403 like this:

```
updater | 2024/06/11 08:19:44 INFO <job_840293070> Starting job processing
  proxy | 2024/06/11 08:19:45 [011] GET https://<host>:443/api/v1/crates/config.json
  proxy | 2024/06/11 08:19:45 [011] * authenticating cargo registry request (url: https://<host>/api/v1/crates/)
  proxy | 2024/06/11 08:19:46 [011] 403 https://<host>:443/api/v1/crates/config.json
updater | 2024/06/11 08:19:46 ERROR <job_840293070> unexpected token at ''
updater | 2024/06/11 08:19:46 ERROR <job_840293070> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
updater | 2024/06/11 08:19:46 ERROR <job_840293070> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
```

It might be just a misconfiguration but would be good to have some confirmation if it works for anyone.

**Comment by jrudolph** [comment]
I figured it out, you just must not use the `Token ` prefix for the Authorization header, so the right config is this:

```
version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    registries:
      - kellnr
    schedule:
      interval: daily

registries:
  kellnr:
    type: cargo-registry
    registry: kellnr
    url: https://<host>/api/v1/crates/
    token: "${{secrets.CRATES_TOKEN}}"
```
