### ISSUE TITLE
Improve host settings

### ISSUE THREAD

**Issue by secana** [kellnr/kellnr#103]
The current settings to configure the address and port where Kellnr runs is confusing.

- `web_address` at start-up as the address
- The port `api_port` sets where Kellnr runs locally
- The `api_address` does not set the address where Kellnr runs locally, but where it is reachable from the outside
- The `api_port_proxy` is the port for external reachability
- The `api_protocol` is for external usage, too

Refactor the settings to make it more clear, what means what.

Idea:

```toml
[local]
# Address where Kellnr binds to. Usually, no change is needed.
address = "0.0.0.0"
# Port where Kellnr binds to.
port = 8000

[external]
# Host from which Kellnr is reachable from the outside.
host = "127.0.0.1"
port = 8000
protocol = "http"
```
