### ISSUE TITLE
Display Cargo config in UI

### ISSUE THREAD

**Issue by secana** [kellnr/kellnr#144]
Display the needed config piece for Cargo to use the current Kellnr instance prominently in the UI.

- [ ] Copy with one click on a button
- [ ] Depending on the enabled features (proxy, required auth) show different config

For example:

_Copy this code to your .cargo/config.toml to use this Kellnr instance_

```toml
[registries]
kellnr = {index = "sparse+https://kellnr.com/api/v1/crates", token = ""}

# IF PROXY IS ENABLED
[source.crates-io]
replace-with = "kellnr-cratesio-sparse"

[source.kellnr-cratesio-sparse]
registry = "sparse+https://kellnr.com/api/v1/cratesio/"

# IF REQUIRED AUTH IS ENABLED
# https://doc.rust-lang.org/nightly/cargo/reference/registry-authentication.html
[registry]
global-credential-providers = ["cargo:token"]
```
