### ISSUE TITLE
failed to download replaced source registry `crates-io`  Caused by: failed to verify the checksum of `bitflags v1.3.2 (registry `kellnr-cratesio`)`

### ISSUE THREAD

**Issue by adrianncovaci** [kellnr/kellnr#169]
I have a droplet setup and Im running kellnr in order to cache crates on that server so that I dont have to refetch them afterwads for other projects. 
This container is running on my remote server:
```bash
docker run --rm -it     -p 8000:8000     -e "KELLNR_ORIGIN__HOSTNAME=hostip"     -e "KELLNR_SETUP__ADMIN_TOKEN=my_super_secret_auth_key"     -e "KELLNR_PROXY__ENABLED=true"     -v $(pwd):/opt/kdata ghcr.io/kellnr/kellnr:5.0.0
```
and this is my `.cargo/toml` file:
```toml
[source.crates-io]
replace-with = "kellnr-cratesio"
[source.kellnr-cratesio]
registry = "sparse+http://hostip:8000/api/v1/cratesio/"
```
When I build the project, I get:
 ```
 error: failed to download replaced source registry `crates-io`
Caused by:
  failed to verify the checksum of `bitflags v1.3.2 (registry `kellnr-cratesio`)`
```
It is properly caching crates from crates.io, since the `crates/` directory gets populated (but fails when downloading the `bitflags` crate). I've also checked with other projects as well and it fails with other crates as well (not necessarily `bitflags`).
