### ISSUE TITLE
proxying only some versions of crates from crates.io

### ISSUE THREAD

**Issue by kemitix** [kellnr/kellnr#183]
Hi,

I'm trying to setup kellnr 5.1.1 to use as a proxy for crates.io, however, when I try to run `cargo fetch` I get the following error:
```
$ cargo fetch
    Updating `kellnr-cratesio` index
error: failed to select a version for the requirement `ahash = "^0.8"`
candidate versions found which didn't match: 0.4.0, 0.3.8, 0.3.7, ...
location searched: `kellnr-cratesio` index (which is replacing registry `crates-io`)
required by package `sqlx-core v0.7.0`
    ... which satisfies dependency `sqlx-core = "=0.7.0"` of package `sqlx v0.7.0`
    ... which satisfies dependency `sqlx = "^0.7"` of package `config-rest-service v2024.1.28 (/home/pcampbell/projects/tasyn/main/crates/services/config-rest-service)`
    ... which satisfies path dependency `config-rest-service` of package `tasyn v2024.1.28 (/home/pcampbell/projects/tasyn/main/crates/main)`
perhaps a crate was updated and forgotten to be re-vendored?
```
This works when my `~/.cargo/config` is unmodified and is contacting crates.io directly.

When I add the following to `~/.cargo/config` I get the error as above:
```ini
[registries]
kellnr = { index = "sparse+https://********:443/api/v1/crates/", token = "***" }
[source.crates-io]
replace-with = "kellnr-cratesio"
[source.kellnr-cratesio]
registry = "sparse+https://********:443/api/v1/cratesio/"
```
When I inspect the cratesio_index table within the sqlite database, I can see that only the first ~49 versions of the ahash crate have been added to the database.
![image](https://github.com/kellnr/kellnr/assets/1147749/7e4102fd-72f9-4792-a471-e3af5af38e96)

**Comment by secana** [comment]
Hi @kemitix!
I tried to reproduce the issue but failed, as `ahash` is correctly pulled on my machine. Can you describe your setup of kellnr for me, such that I can replicate it? 

Do you use Kellnr on bare metal or as a container? Do you use the sqlite or postgresdb backend?

**Comment by kemitix** [comment]
Hi @secana 

Here is my `docker-compose.yml`:
```yaml
version: "3.3"
services:
  kellnr:
    image: ghcr.io/kellnr/kellnr:5.1.1@sha256:50ed600736e1b561eaf2c1bf960f7d320e5d4525ae0c6574d380f8d033526f8a
    restart: unless-stopped
    volumes:
      - ./data:/opt/kdata
    ports:
      - 8089:8000
    environment:
      KELLNR_ORIGIN__PROTOCOL: https
      KELLNR_ORIGIN__HOSTNAME: crates.***.net
      KELLNR_ORIGIN__PORT: 443
      # KELLNR_LOG__LEVEL: trace
      KELLNR_REGISTRY__MAX_CRATE_SIZE: 1000
      KELLNR_PROXY__ENABLED: true
      KELLNR_DOCS__ENABLED: true
      KELLNR_DOCS__MAX_SIZE: 1000
```

It is hosted behind Caddy as a reverse proxy:
```
https://crates.***.net:443 {
    reverse_proxy :8089
}
```
