### ISSUE TITLE
I can not figure out how to set it up correctly

### ISSUE THREAD

**Issue by xNxExOx** [kellnr/kellnr#219]
I followed the instructions https://kellnr.io/documentation, I set the hostname, and I also tried to set it up using an IP, but neither worked for me. I I tried docker, and local serveice, but switched to starting it manully to see the console directly.
When I try to publish empty crate, I will get this error in console:
> DEBUG request: tower_http::trace::on_response: finished processing request latency=2 ms status=404 method=GET uri=/api/v1/crates/info/refs?service=git-upload-pack version=HTTP/1.0

When I try to add dependency:
`polars = { version = "0.38.1", features = ["csv", "http"], registry = "my-registry" }`
>  DEBUG request: tower_http::trace::on_response: finished processing request latency=0 ms status=404 method=GET uri=/api/v1/crates/info/refs?service=git-upload-pack version=HTTP/1.0

And local error:
> fatal: repository 'https://test.bandola.cz/api/v1/crates/' not found
> error: failed to get `polars` as a dependency of package `polars_test v0.1.0 (D:\rs\polars_test)`
> Caused by:
>   failed to load source for dependency `polars`
> Caused by:
>   Unable to update registry `my-registry`
> Caused by:
>   failed to fetch `https://test.bandola.cz/api/v1/crates/`
> Caused by:
>   process didn't exit successfully: `git fetch --force --update-head-ok https://test.bandola.cz/api/v1/crates/ +HEAD:refs/remotes/origin/HEAD` (exit code: 128)

if I add the dependency like this:
`polars = { version = "0.38.1", features = ["csv", "http"] }`
> DEBUG request: tower_http::trace::on_response: finished processing request latency=0 ms status=200 method=GET uri=/api/v1/crates/config.json version=HTTP/1.0
> DEBUG request: tower_http::trace::on_response: finished processing request latency=1 ms status=404 method=GET uri=/api/v1/crates/po/la/polars version=HTTP/1.0

And local error:
> cargo.exe build --color=always --message-format=json-diagnostic-rendered-ansi --package polars_test --bin polars_test
>     Updating `kellnr-cratesio` index
> error: no matching package named `polars` found
> location searched: registry `crates-io`
> required by package `polars_test v0.1.0 (D:\rs\polars_test)`

My config.toml:
```toml
[registries]
#my-registry = { index = "sparse+https://test.bandola.cz/api/v1/crates/", token = " actual token " }
my-registry = { index = "https://test.bandola.cz/api/v1/crates/", token = " actual token " }

[source.crates-io]
replace-with = "kellnr-cratesio"

[source.kellnr-cratesio]
registry = "sparse+https://test.bandola.cz/api/v1/crates/"
#registry = "sparse+http://192.168.0.112:8000/api/v1/crates/"
#index = "sparse+http://192.168.0.112:8000/api/index/"


[net]
git-fetch-with-cli = true
```

The commented lines are just some of the examples what I tried. I have token I created in UI there, not `" actual token "`, but did not want to include that in a public report.

Can you please help me figure out how to set it up correctly? I want it to be mostly internal mirror of crates.io with some private crates.

**Comment by secana** [comment]
Hi! Try it with the config below.

```toml
[registries]
my-registry = { index = "sparse+https://test.bandola.cz/api/v1/crates/", token = " actual token " } # sparse is required

[source.crates-io]
replace-with = "kellnr-cratesio"

[source.kellnr-cratesio]
registry = "sparse+https://test.bandola.cz/api/v1/cratesio/" # cratesio NOT crates!
```

If you want to pull polars through kellnr, you do not have to specify the registry.

`polars = { version = "0.38.1", features = ["csv", "http"] }` is enough. You only need to specify the registry for your own packages. The proxy is transparent.

If something still doesn't work. Let me know.
