### ISSUE TITLE
Click re-build / build button (for document) in web UI return 401 Unauthorized

### ISSUE THREAD

**Issue by visig9** [kellnr/kellnr#356]
Click `re-build` or `build` button (for document) in web UI return `401 Unauthorized`.

### Log

```
2024-06-13T05:40:55.248213Z  WARN auth::auth_req_token: Authentication required, but failed: 401 Unauthorized
```

### Startup command

```sh
sudo docker run --name kellnr --restart always -d \
    -p 8089:8089 \
    -e 'KELLNR_ORIGIN__HOSTNAME=mycrates.example.com' \
    -e 'KELLNR_ORIGIN__PROTOCOL=https' \
    -e 'KELLNR_ORIGIN__PORT=443' \
    -e 'KELLNR_LOCAL__PORT=8089' \
    -e 'KELLNR_DOCS__ENABLED=true' \
    -e 'KELLNR_REGISTRY__AUTH_REQUIRED=true' \
    -v '/var/lib/kellnr:/opt/kdata' \
    -v '/etc/kellnr/cargo-config.toml:/root/.cargo/config.toml:ro' \
    ghcr.io/kellnr/kellnr:5.2.3
```

### `.cargo/config.toml`:

```toml
[registries.mycrates]
index = "sparse+https://mycrates.example.com/api/v1/crates/"
credential-provider = ["cargo:token"]
token = "SECRET"
```
