### ISSUE TITLE
example config should contains `credential-provider` setting

### ISSUE THREAD

**Issue by visig9** [kellnr/kellnr#357]
The following doc ...

```toml
[registries]
kellnr = { index = "sparse+https://yourkellnrhostname/api/v1/crates/", token = "yourauthtoken" }
```

At locations:

- https://kellnr.io/documentation#global-config
- https://kellnr.io/documentation#rustdoc

...  not work out of the box due to user should also configure [registries.name.credential-provider](https://doc.rust-lang.org/cargo/reference/config.html#registriesnamecredential-provider) or [registry.global-credential-providers](https://doc.rust-lang.org/cargo/reference/config.html#registryglobal-credential-providers). And the cargo documentation are more or less misleading.

See this issue: https://github.com/rust-lang/cargo/issues/13343

## Suggestion

Use this one as example:

```toml
[registries.kellnr]
index = "sparse+https://yourkellnrhostname/api/v1/crates/"
credential-provider = ["cargo:token"]
token = "yourauthtoken"
```
