### ISSUE TITLE
5.2.4 Doc build failed: Authentication required, but failed: 401 Unauthorized

### ISSUE THREAD

**Issue by visig9** [kellnr/kellnr#414]
I have 2 crates uploaded to my Kellnr server call `myreg`:

- crate: `myproj-core`: just a normal crate but uploaded to `myreg`.
- crate: `myproj`: use `myproj-core` as dependency and also uploaded to `myreg` too.

```toml
# myproj's Cargo.toml

# ... OMITTED ...

[dependencies]
# use both `version` and `path` because I'm in a workspace, See: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations
myproj-core = { version = "0.1.0", path = "../myproj-core", registry = "myreg" }

# ... OMITTED ...
```

Use `cargo publish -p myproj` or click `build` button within kellnr's webui, I got some error message like this:

```sh
ubuntu@ip-172-33-44-55:~$ sudo docker logs kellnr -f
# ... OMITTED ...
    Updating `sparse+https://crates.myreg.com/api/v1/crates/` index
    Updating crates.io index
2024-08-09T06:23:53.880650Z  WARN auth::auth_req_token: Authentication required, but failed: 401 Unauthorized
2024-08-09T06:23:53.996783Z ERROR docs::doc_queue: Failed to extract docs from crate: failed to get `myproj-core` as a dependency of package `myproj v0.1.0 (/opt/kdata/doc_queue/weYg3JRVvH/myproj-0.1.0)`
```

Try to make sure `/root/.cargo/config.toml` correct:

```sh
ubuntu@ip-172-33-44-55:~$ sudo docker exec -it kellnr bash

root@0912c1335120:/opt/kellnr# cat /root/.cargo/config.toml
[registries.myreg]
index = "sparse+https://crates.myreg.com/api/v1/crates/"
credential-provider = ["cargo:token"]
token = "<HIDDEN1>"

root@0912c1335120:/opt/kellnr# exit

ubuntu@ip-172-33-44-55:~$ sqlite3 -header -column /var/lib/kellnr/db.sqlite "SELECT * FROM auth_token"
id  name            token                             user_fk
--  --------------  --------------------------------  -------
7   server-itself   <HIDDEN1>                         1
9   mac-2024        <HIDDEN2>                         7
```

> NOTE: two `<HIDDEN1>` are the same.

## My Kellnr startup script

```sh
sudo docker run -d \
    --name kellnr \
    --restart always \
    -p 8089:8089 \
    -e 'KELLNR_LOCAL__PORT=8089' \
    -e 'KELLNR_ORIGIN__PROTOCOL=https' \
    -e 'KELLNR_ORIGIN__HOSTNAME=crates.myreg.com' \
    -e 'KELLNR_ORIGIN__PORT=443' \
    -e 'KELLNR_DOCS__ENABLED=true' \
    -e 'KELLNR_REGISTRY__AUTH_REQUIRED=true' \
    -e 'KELLNR_REGISTRY__SESSION_AGE_SECONDS=1209600' \
    -v '/var/lib/kellnr:/opt/kdata' \
    -v '/etc/kellnr/cargo-config.toml:/root/.cargo/config.toml:ro' \
    ghcr.io/kellnr/kellnr:5.2.4
```
