### ISSUE TITLE
Docker variable seems to notuse the port config correctly.

### ISSUE THREAD

**Issue by NicTanghe** [kellnr/kellnr#621]
So i ran into the issue that when i was trying to use kellnr it kept pointing to port 8000 locally even though i set up evrything to use port  50000, or so i thought.

when i want to go lookin in default.toml.

the port still read port 8000

here`s the compose i used.
```
version: '3.8'

services:
  kellnr:
    container_name: kellnr-cargo-regestry  # Custom container name
    image: ghcr.io/kellnr/kellnr:5.0.0
    ports:
      - "50000:50000"  # high port to avoid default scans
    environment:
      - KELLNR_ORIGIN__HOSTNAME=********
      - KELLNR_SETUP__ADMIN_PWD=********
      - KELLNR_LOCAL__PORT=50000
    volumes:
      - /shares/versioning/rust-cargo-regestry:/opt/kdata
    restart: unless-stopped
```

when i changed the variable in the default config to 5000 the website was no longer accassible via http://*********:50000/ like it was before.

the docker container now also disconnects after 3 seconds.
