### ISSUE TITLE
Cannot use crates.io proxy

### ISSUE THREAD

**Issue by NeroReflex** [kellnr/kellnr#641]
Hello and sorry if I have made some silly mistakes.

I am trying to use kellnr to have a private registry and have therefore referred to to the documentation on how to achieve that:

```
KELLNR_PROXY__ENABLED=true
KELLNR_PROXY__NUM_THREADS=5
```

this is given in the web ui so it appears it is configured correctly in this regard.

my .cargo/config.toml

```
[source.crates-io]
replace-with = "kellnr"

[registries.kellnr]
index = "sparse+https://url/api/v1/crates/"
credential-provider = ["cargo:token"]
token = "xxxxxxxxxxxxxxxxxxxxxxxx"
```

the registry is working: I can publish to it. In fact if I try to re-publish a crate this error appears:

```
error: crate crate_name@1.1.0 already exists on `kellnr` index
```

However if I try to publish something that depends on a crate from a crates.io this happens:

```
error: crates-io is replaced with remote registry kellnr;
include `--registry kellnr` or `--registry crates-io`

# so I include --registry kellnr
cargo publish --registry kellnr
    Updating `kellnr` index
    Updating `kellnr` index
error: no matching package named `nix` found
location searched: `kellnr` index (which is replacing registry `crates-io`)
required by package `another_crate_name v0.2.4 (/storage/path)`
```

So I am stuck like this and I have no idea how to properly make kellnr to seamlessly proxy crates.io.

I have installed from AUR yestarday.

**Comment by secana** [comment]
Hi! When kellnr is configured as a crates.io proxy, it exports two different registries. One for your own crates and one as a proxy for crates.io. That's because you do not want naming conflicts between the two. 

It seems that you've only configured the first one in your `config.toml`. That's why you can push your own crates, but the proxy does not work. 

Have a look at this section of the docs: https://kellnr.io/documentation#replace-cratesio

Your config should look similar to this:

```toml
[source.crates-io]
replace-with = "kellnr-cratesio"

[registries.kellnr]
index = "sparse+https://url/api/v1/crates/"
credential-provider = ["cargo:token"]
token = "xxxxxxxxxxxxxxxxxxxxxxxx"

[registries.kellnr-cratesio]
index = "sparse+https://yourkellnrhostname/api/v1/cratesio/"
```
